---
# Secret containing registry credentials
kind: secret
name: registry
get:
  path: registries
  name: quay-io.conf
---
# Build image for AMD64
kind: pipeline
type: docker
name: build-amd64

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone ${DRONE_GIT_HTTP_URL} .
      - git checkout $DRONE_COMMIT
  - name: credential
    # 3.17.0
    image: docker.io/alpine@sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4
    volumes:
      - name: dockercredentials
        path: /root/.docker
    environment:
      REGISTRY:
        from_secret: registry
    commands:
      - /bin/echo $${REGISTRY} > ~/.docker/config.json
  - name: build
    # 20-dind
    image: docker.io/docker@sha256:80e81aecd51d80e63ae4cbbd5eb1968e84edd151b90ef2c2f17e1004c7a3832b
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      # Wait that the docker daemon start
      - while ! [ -e /var/run/docker.sock ]; do /bin/sleep 0.5; done
      # Display docker version (for CI log)
      - /usr/local/bin/docker version
      - /usr/local/bin/docker info
      # Build the image
      - /usr/local/bin/docker build -t "${DRONE_COMMIT_SHA}" --rm=true -f Dockerfile . --pull=true --label org.opencontainers.image.created=$$(/bin/date --utc +"%Y-%m-%dT%H:%M:%SZ") --label org.opencontainers.image.revision=${DRONE_COMMIT} --label org.opencontainers.image.source=${DRONE_GIT_HTTP_URL}
  - name: tag-push
    when:
      event:
        - tag
      ref:
        - refs/tags/v*
    # 20-dind
    image: docker.io/docker@sha256:80e81aecd51d80e63ae4cbbd5eb1968e84edd151b90ef2c2f17e1004c7a3832b
    volumes:
      - name: dockersock
        path: /var/run
      - name: dockercredentials
        path: /root/.docker
    commands:
      # Tag and push image
      - /usr/local/bin/docker tag "${DRONE_COMMIT_SHA}" "quay.io/lolo32/kube-tools:${DRONE_TAG}-amd64"
      - /usr/local/bin/docker push "quay.io/lolo32/kube-tools:${DRONE_TAG}-amd64"
      # Save .RepoDigest for next step
      - /usr/local/bin/docker image inspect --format "{{index .RepoDigests 0}}" "quay.io/lolo32/kube-tools:${DRONE_TAG}-amd64" > image.sha256
  - name: sign
    when:
      event:
        - tag
      ref:
        - refs/tags/v*
    # 3.17.0
    image: docker.io/alpine@sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4
    volumes:
      - name: dockercredentials
        path: /root/.docker
    environment:
      COSIGN_EXPERIMENTAL: "1"
    commands:
      # Install Cosign
      - apk add curl
      - curl -sSLo /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v1.13.1/cosign-linux-amd64 -sSLO https://github.com/sigstore/cosign/releases/download/v1.13.1/cosign-linux-amd64.sig
      - chmod 0755 /usr/local/bin/cosign
      - /usr/local/bin/cosign verify-blob --key release-cosign.pub --signature cosign-linux-amd64.sig /usr/local/bin/cosign
      # Sign the .RepoDigest
      - cosign sign "$$(cat image.sha256)"

services:
  - name: docker-service
    # 20-dind
    image: docker.io/docker@sha256:80e81aecd51d80e63ae4cbbd5eb1968e84edd151b90ef2c2f17e1004c7a3832b
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
  - name: dockercredentials
    temp: {}
---
# Build image for ARM64
kind: pipeline
type: docker
name: build-arm64

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
  - name: clone
    # 2.36.3
    image: alpine/git@sha256:66b210a97bc07bfd4019826bcd13a488b371a6cbe2630a4b37d23275658bd3f2
    commands:
      - git clone ${DRONE_GIT_HTTP_URL} .
      - git checkout $DRONE_COMMIT
  - name: credential
    # 3.17.0
    image: docker.io/alpine@sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4
    volumes:
      - name: dockercredentials
        path: /root/.docker
    environment:
      REGISTRY:
        from_secret: registry
    commands:
      - /bin/echo $${REGISTRY} > ~/.docker/config.json
  - name: build
    # 20-dind
    image: docker.io/docker@sha256:80e81aecd51d80e63ae4cbbd5eb1968e84edd151b90ef2c2f17e1004c7a3832b
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      # Wait that the docker daemon start
      - while ! [ -e /var/run/docker.sock ]; do /bin/sleep 0.5; done
      # Display docker version (for CI log)
      - /usr/local/bin/docker version
      - /usr/local/bin/docker info
      # Build the image
      - /usr/local/bin/docker build -t "${DRONE_COMMIT_SHA}" --rm=true -f Dockerfile . --pull=true --label org.opencontainers.image.created=$$(/bin/date --utc +"%Y-%m-%dT%H:%M:%SZ") --label org.opencontainers.image.revision=${DRONE_COMMIT} --label org.opencontainers.image.source=${DRONE_GIT_HTTP_URL}
  - name: tag-push
    when:
      event:
        - tag
      ref:
        - refs/tags/v*
    # 20-dind
    image: docker.io/docker@sha256:80e81aecd51d80e63ae4cbbd5eb1968e84edd151b90ef2c2f17e1004c7a3832b
    volumes:
      - name: dockersock
        path: /var/run
      - name: dockercredentials
        path: /root/.docker
    commands:
      # Tag and push image
      - /usr/local/bin/docker tag "${DRONE_COMMIT_SHA}" "quay.io/lolo32/kube-tools:${DRONE_TAG}-arm64"
      - /usr/local/bin/docker push "quay.io/lolo32/kube-tools:${DRONE_TAG}-arm64"
      # Save .RepoDigest for next step
      - /usr/local/bin/docker image inspect --format "{{index .RepoDigests 0}}" "quay.io/lolo32/kube-tools:${DRONE_TAG}-arm64" > image.sha256
  - name: sign
    when:
      event:
        - tag
      ref:
        - refs/tags/v*
    # 3.17.0
    image: docker.io/alpine@sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4
    volumes:
      - name: dockercredentials
        path: /root/.docker
    environment:
      COSIGN_EXPERIMENTAL: "1"
    commands:
      # Install Cosign
      - apk add curl
      - curl -sSLo /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v1.13.1/cosign-linux-arm64 -sSLO https://github.com/sigstore/cosign/releases/download/v1.13.1/cosign-linux-arm64.sig
      - chmod 0755 /usr/local/bin/cosign
      - /usr/local/bin/cosign verify-blob --key release-cosign.pub --signature cosign-linux-arm64.sig /usr/local/bin/cosign
      # Sign the .RepoDigest
      - cosign sign "$$(cat image.sha256)"

services:
  - name: docker-service
    # 20-dind
    image: docker.io/docker@sha256:80e81aecd51d80e63ae4cbbd5eb1968e84edd151b90ef2c2f17e1004c7a3832b
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
  - name: dockercredentials
    temp: {}
---
# Manifest multi-architecture
kind: pipeline
type: docker
name: manifest

depends_on:
  - build-amd64
  - build-arm64

trigger:
  event:
    - tag
  ref:
    - refs/tags/v*

steps:
  - name: credential
    # 3.17.0
    image: docker.io/alpine@sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4
    volumes:
      - name: dockercredentials
        path: /root/.docker
    environment:
      REGISTRY:
        from_secret: registry
    commands:
      - /bin/echo $${REGISTRY} > ~/.docker/config.json
  - name: manifest
    # 20-dind
    image: docker.io/docker@sha256:80e81aecd51d80e63ae4cbbd5eb1968e84edd151b90ef2c2f17e1004c7a3832b
    volumes:
      - name: dockersock
        path: /var/run
      - name: dockercredentials
        path: /root/.docker
    commands:
      # Wait that the docker daemon start
      - while ! [ -e /var/run/docker.sock ]; do /bin/sleep 0.5; done
      # Display docker version (for CI log)
      - /usr/local/bin/docker version
      - /usr/local/bin/docker info
      # Multi-architecture tag
      - /usr/local/bin/docker manifest create "quay.io/lolo32/kube-tools:${DRONE_TAG}" "quay.io/lolo32/kube-tools:${DRONE_TAG}-amd64" "quay.io/lolo32/kube-tools:${DRONE_TAG}-arm64"
      - /usr/local/bin/docker manifest push --purge "quay.io/lolo32/kube-tools:${DRONE_TAG}"
      # Save .RepoDigest for next step
      - /usr/local/bin/docker pull "quay.io/lolo32/kube-tools:${DRONE_TAG}"
      - /usr/local/bin/docker inspect --format "{{index .RepoDigests 0}}" "quay.io/lolo32/kube-tools:${DRONE_TAG}" > image.sha256
  - name: sign
    # 3.17.0
    image: docker.io/alpine@sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4
    volumes:
      - name: dockercredentials
        path: /root/.docker
    environment:
      COSIGN_EXPERIMENTAL: "1"
    commands:
      # Install Cosign
      - apk add curl
      - curl -sSLo /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v1.13.1/cosign-linux-arm64 -sSLO https://github.com/sigstore/cosign/releases/download/v1.13.1/cosign-linux-arm64.sig
      - chmod 0755 /usr/local/bin/cosign
      - /usr/local/bin/cosign verify-blob --key release-cosign.pub --signature cosign-linux-arm64.sig /usr/local/bin/cosign
      # Sign the .RepoDigest
      - cosign sign "$$(cat image.sha256)"

services:
  - name: docker
    # 20-dind
    image: docker.io/docker@sha256:80e81aecd51d80e63ae4cbbd5eb1968e84edd151b90ef2c2f17e1004c7a3832b
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
  - name: dockercredentials
    temp: {}
